language: python
dist: xenial  # req'd for python >= 3.7
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- pypy
- pypy3
install:
- pip install -q '.[dev]'
script:
- nosetests
deploy:
  provider: pypi
  user: daveshawley
  password:
    secure: GlAK7LyPin+goUjr1Vb6MJmI3duzihL3lyutfyZpmNz1BONbe3LZZB05FnoQLDPQGBVp0EpBnsgdsngtmumxBVbn5TJ8/oUNRUYfLOBrUyEFKurd8IDgfh1lJ+LtQvbZgie5hLG7DkHPr4gf0Gz4AIewrx9rypDc4Q8aerR2Suw=
  distributions: sdist bdist_wheel
  on:
    tags: true
    all_branches: true
    python: 3.7
